# Generated by Django 4.1.3 on 2022-11-22 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='popo', max_length=255, verbose_name='Имя')),
                ('state', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='alfaBitTask.leadstate', verbose_name='Состояние')),
            ],
        ),
    ]
